workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Force Gradle 8.5 Wrapper
        script: |
          gradle wrapper --gradle-version 8.5 --distribution-type bin
          chmod +x gradlew
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
