workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      java: 21
    scripts:
      - name: Force Gradle 9.3.1 Wrapper
        script: |
          gradle wrapper --gradle-version 9.3.1 --distribution-type bin
          chmod +x gradlew
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug -Pandroid.injected.signing.store.file=""
    artifacts:
      - app/build/outputs/**/*.apk
